-- AlterTable
ALTER TABLE "FinanceData" ALTER COLUMN "BTC" SET DATA TYPE TEXT,
ALTER COLUMN "NYSE" SET DATA TYPE TEXT,
ALTER COLUMN "LSE" SET DATA TYPE TEXT,
ALTER COLUMN "BTC_Volume" SET DATA TYPE TEXT,
ALTER COLUMN "NYSE_Volume" SET DATA TYPE TEXT,
ALTER COLUMN "LSE_Volume" SET DATA TYPE TEXT;
